services:
  libra-node:
    image: petticur/libra-node:stack
    # Note at present uid/gid only works for 1000
    # since the user ubuntu has that uid and already
    # has a home directory at /home/ubuntu
    # So bind mounting will randomly fail if the host
    # user has a uid that is not 1000 (very likely to be the case).
    user: ${STACK_HOST_UID:-1000}:${STACK_HOST_GID:-1000}
    volumes:
      - libra-storage:/home/ubuntu/.libra
    ports:
      - 6182
      - 8080 # @stack http-proxy

volumes:
  libra-storage:
