services:
  libra-node:
    image: 0lnetworkcommunity/libra-node:stack
    # Pass the host uid:gid to allow the container to set file ownership correctly
    environment:
      USER_UID: ${STACK_HOST_UID}
      USER_GID: ${STACK_HOST_GID}
    volumes:
      - libra-storage:/mnt/libra/.libra
    ports:
      - 6182
      - 8080 # @stack http-proxy

volumes:
  libra-storage:
